name: Deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  deploy-app1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy app1
        uses: azure/webapps-deploy@v2
        with:
          app-name: <Your-App-Service-Name>
          slot-name: production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D1FCBE07276F494C94A0E3DA5975E2E9_APP1 }}

  deploy-app2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy app2
        uses: azure/webapps-deploy@v2
        with:
          app-name: <Your-App-Service-Name>
          slot-name: production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D1FCBE07276F494C94A0E3DA5975E2E9_APP2 }}

          
           
         
